# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "ap-south-1"
  assume_role {
      session_name = "terraform"
      role_arn = "arn:aws:iam::730335384723:role/atlantis-role"
    }
}
