# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-bucket"
    dynamodb_table = "terraform-lock-table"
    encrypt        = true
    key            = "eks/terraform.tfstate"
    region         = "ap-south-1"
    role_arn       = "arn:aws:iam::730335384723:role/atlantis-role"
  }
}
