# Docker Hub Image Pull Secret
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIloyOXJkWEpoYWpwQ2FHRnphSGxoYlVBeCIKCQl9Cgl9Cn0=