
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"  # Ensure the port matches the target port of your service
    prometheus.io/path: "/metrics"
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: python-app

