{
 "title": "Observability data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "findMatch", "label": "Find match in Application Logs" },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Error Requests ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_errors_total{job=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Call Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_call_latency_seconds_sum{job=\"$service\"} / api_call_latency_seconds_count{job=\"$service\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of Requests made based by Status Code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"$service\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "No of Requests made",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio (%)",
   "type": "gauge",
   "description": "Shows the current cache hit ratio as a percentage, providing a quick efficiency metric.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cache_hits_total{job=\"$service\"}[$__range]) / (rate(cache_hits_total{job=\"$service\"}[$__range]) + rate(cache_misses_total{job=\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg((http_request_duration_seconds_sum{job=\"$service\"} / http_request_duration_seconds_count{job=\"$service\"})*1000) by (method, path, status_code)\r\n",
     "legendFormat": "{{method}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency Distribution Heatmap",
   "type": "heatmap",
   "description": "This heatmap visualizes the distribution of request latencies over time, helping you identify patterns and trends in how long requests take to complete. The X-axis represents time, while the Y-axis shows latency buckets (in milliseconds)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[$__range])) by (le)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Operations by time range",
   "type": "stat",
   "description": "Shows the total number of operations in the last hour, providing a quick overview.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(business_logic_operations_total{job=\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Business Logic Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(business_logic_operations_total{job=\"$service\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces of Application",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "filters": [
      { "id": "f0d79308", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$service\"} |~ `(?i)$findMatch`"
    }
   ]
  }
 ]
}