{
 "title": "Kubescape",
 "time": { "from": "now-10s", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(failed_resource_remediations{job=\"kubernetes-service-endpoints\"},namespace)"
    }
   },
   {
    "name": "resource_name",
    "label": "resource_name",
    "query": {
     "query": "label_values(failed_resource_remediations{namespace=\"$namespace\"},resource)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Kubescape Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Compliance Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_compliance_score ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Framework scores",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "framework_compliance_score{job=\"kubernetes-service-endpoints\", framework!=\"AllControls\"}",
     "legendFormat": "{{framework}}"
    }
   ]
  },
  {
   "title": "Failed Resources by Severity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "failed_resources_severity{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Failed Resources by Issue Names",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(issue_name) (failed_resource_issues{job=\"kubernetes-service-endpoints\"})",
     "legendFormat": "{{ issue_name }}"
    }
   ]
  },
  { "title": "Detailed Report Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "failed_resource_remediations{job=\"kubernetes-service-endpoints\", namespace=\"$namespace\", resource=\"$resource_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}