apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: json-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: {{ .Values.volume.storageClassName }}
  volumeName: json-pv
