apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescape-metrics-sa
  namespace: default  # Adjust to your namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescape-crd-reader
rules:
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["workloadconfigurationscans", "workloadconfigurationscansummaries"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubescape-crd-reader-binding
subjects:
- kind: ServiceAccount
  name: kubescape-metrics-sa
  namespace: default  # Adjust to your namespace
roleRef:
  kind: ClusterRole
  name: kubescape-crd-reader
  apiGroup: rbac.authorization.k8s.io