
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescape-metrics-exporter
  namespace: default
  labels:
    app: kubescape-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubescape-metrics-exporter
  template:
    metadata:
      labels:
        app: kubescape-metrics-exporter
    spec:
      serviceAccountName: kubescape-metrics-sa
      containers:
      - name: metrics-exporter
        image: gokuraj/kubescape:crd2
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: kubescape-metrics
  namespace: default
  labels:
    app: kubescape-metrics
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kubescape-metrics-exporter
