repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
    
  - name: grafana
    url: https://grafana.github.io/helm-charts

  - name: fluent
    url: https://fluent.github.io/helm-charts

  - name: prometheus-msteams
    url: https://prometheus-msteams.github.io/prometheus-msteams

  - name: kubescape
    url: https://kubescape.github.io/helm-charts/


releases:
  - name: prometheus
    chart: prometheus/prometheus
    version: "27.8.*"
    values:
      - ./values/prometheus.yaml
    labels:
      tool: prometheus

  - name: loki-distributed
    chart: grafana/loki-distributed
    version: "0.80.*"
    values:
      - ./values/loki-distributed.yaml
    labels:
      tool: loki-distributed

  - name: grafana
    chart: grafana/grafana
    version: "8.11.*" 
    values:
      - ./values/grafana_values.yaml
    labels:
      tool: grafana

  - name: alloy
    chart: grafana/alloy
    version: "0.12.*"
    values:
      - ./values/alloy_values.yaml
    labels:
      tool: alloy

  - name: tempo-distributed
    chart: grafana/tempo-distributed
    version: "1.33.*" 
    values:
      - ./values/tempo_values.yaml
    labels:
      tool: tempo-distributed

  - name: alertmanager
    chart: prometheus/alertmanager
    version: "1.16.*"
    values: 
      - ./values/alertmanager_values.yaml
    labels:
      tool: alertmanager

  - name: fluent
    chart: fluent/fluent-bit
    version: "0.48.*"
    values:
      - ./values/fluentbit_values.yaml
    labels:
      tool: fluent

  - name: prometheus-msteams
    chart: prometheus-msteams/prometheus-msteams
    version: "1.3.4"
    values:
      - ./values/prometheus-msteams_values.yaml
    labels:
      tool: msteams

  - name: kubescape
    chart: kubescape/kubescape-operator
    version: "1.27.*"
    values:
      - ./values/kubescape_values.yaml
    labels:
      tool: kubescape
      