# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "asista-terragrunt-state-prod-account"
    dynamodb_table = "terraform-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-south-1"
    role_arn       = "arn:aws:iam::703671898773:role/terraform-assumed-role-shared-prod"
  }
}