apiVersion: v2
name: observability-stack
description: A Helm chart to deploy Grafana, Tempo, Alloy, and Loki together
version: 1.0.0
appVersion: "1.0"



dependencies:
  - name:        grafana
    version:     "8.11.*"  
    repository:  "https://grafana.github.io/helm-charts"
    condition:   grafana.enabled

  - name:        tempo-distributed
    version:     "1.33.*" 
    repository:  "https://grafana.github.io/helm-charts"
    condition:   tempo-distributed.enabled

  - name:        loki-distributed
    version:     "0.80.*" 
    repository:  "https://grafana.github.io/helm-charts"
    condition:   loki-distributed.enabled

  - name:        alloy
    version:     "0.12.*"  
    repository:  "https://grafana.github.io/helm-charts"
    condition:   alloy.enabled

  - name:        prometheus
    version:     "27.8.*"
    repository:  "https://prometheus-community.github.io/helm-charts"
    condition:   prometheus.enabled
  
  - name:        fluent-bit
    version:     "0.48.*"
    repository:  "https://fluent.github.io/helm-charts"
    condition:   fluentbit.enabled

  - name:        alertmanager
    version:     "1.16.*"
    repository:  "https://prometheus-community.github.io/helm-charts"
    condition:   alertmanager.enabled
  
  - name:       prometheus-msteams
    version:    "1.3.4"
    repository:  https://prometheus-msteams.github.io/prometheus-msteams
    condition:   prometheus-msteams.enabled
  
  - name:        kubescape
    version:     "0.1.0"
    repository:  "file://kubescape"
    condition:   kubescape.enabled

  - name:        prometheus-blackbox-exporter
    version:     "9.5.*"
    repository:  "https://prometheus-community.github.io/helm-charts"
    condition:   prometheus-blackbox-exporter.enabled
