{
 "title": "Kubescape",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(failed_resource_remediations,namespace)"
    }
   },
   {
    "name": "resource_name",
    "label": "resource_name",
    "query": {
     "query": "label_values(failed_resource_remediations{namespace=\"$namespace\"},resource)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resources by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubescape_control_count_resources_passed)",
     "legendFormat": "Passed"
    },
    {
     "expr": "sum(kubescape_control_count_resources_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kubescape_control_count_resources_skipped)",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "Compliance Score by framework",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubescape_framework_complianceScore) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Resources by Severity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "failed_resources_severity{job=\"json_metrics\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "failed_resource_remediations{job=\"json_metrics\", resource=\"$resource_name\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Observability data",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Traces of Application",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "f0d79308", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "my-python-service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "No of Requests made",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_counter_total{job=\"my-python-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"my-python-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Kubernetes Resources Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\"} |= ``"
    }
   ]
  }
 ]
}